name: master
channels:
  - pytorch
  - nvidia
  - conda-forge
dependencies:
  - python>=3.8
  - pip
  - jupyterlab
  - pandas
  - matplotlib
  - numpy
  - scipy
  - scikit-learn
  - seaborn
  - pytorch-cuda=12.3
  - torchvision
  - pip:
    - -e ./src/code