name: master
channels:
  - conda-forge
dependencies:
  - python
  - pip
  - pip:
    - jupyterlab
    - pandas
    - matplotlib
    - numpy
    - scipy
    - scikit-learn
    - seaborn
    - torch
    - torchvision
